# -*- coding: utf-8 -*-
"""Tugas_11_Machine_Translation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17kJ1HpBadO6FlOAo03NDUU3HBUgjmAI5
"""

import nltk
from nltk.translate import Alignment, AlignedSent
from nltk.translate import IBMModel1

"""Definisi korpus yang berisi bahasa indonesia dan jawa."""

als = []

als.append(AlignedSent( ["saya", "mau", "tidur" ], \
    ["kulo", "bade", "bobo"] , \
    Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
als.append(AlignedSent( ["saya", "sedang", "lapar" ], \
    ["kulo", "nembe", "luwe"] , \
    Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
als.append(AlignedSent( ["ayah", "sudah", "makan" ], \
    ["bapak", "sampun", "dahar"] , \
    Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
als.append(AlignedSent( ["ayah", "ingin", "pergi" ], \
    ["bapak", "bade", "tindak"] , \
    Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
als.append(AlignedSent( ["ibu", "makan", "ayam" ], \
    ["ibu", "dahar", "ayam"] , \
    Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))

als.append(AlignedSent( ["ibu", "beli", "makanan" ], \
    ["ibu", "tumbas", "jajanan"] , \
    Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
als.append(AlignedSent( ["kaca", "itu", "pecah" ], \
    ["koco", "niku", "pecah"] , \
    Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
als.append(AlignedSent( ["telur", "itu", "pedas" ], \
    ["endog", "niku", "pedes"] , \
    Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
als.append(AlignedSent( ["air", "itu", "jatuh" ], \
    ["toyo", "niku", "dawah"] , \
    Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
als.append(AlignedSent( ["kakak", "sedang", "bermain" ], \
    ["mas", "nembe", "maen"] , \
    Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))

als.append(AlignedSent( ["kakak", "sedang", "tidur" ], \
    ["mbak", "nembe", "bobo"] , \
    Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
als.append(AlignedSent( ["tante", "mau", "datang" ], \
    ["bude", "bade", "rawuh"] , \
    Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
als.append(AlignedSent( ["tante", "makan", "lele" ], \
    ["bude", "dahar", "lele"] , \
    Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
als.append(AlignedSent( ["om", "datang", "ke", "rumah" ], \
    ["pakde", "rawuh", "teng", "dalem"] , \
    Alignment( [ (0 , 0), (1 , 1), (2 , 2), (3 , 3) ] ) ))
als.append(AlignedSent( ["nenek", "masak", "telur" ], \
    ["mbah", "masak", "endog"] , \
    Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))

als.append(AlignedSent( ["kakek", "memberi", "uang" ], \
    ["kakung", "maringi", "arto"] , \
    Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
als.append(AlignedSent( ["kakek", "menanam", "padi" ], \
    ["kakung", "nandur", "pari"] , \
    Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
als.append(AlignedSent( ["nenek", "masak", "nasi" ], \
    ["mbah", "masak", "sekul"] , \
    Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
als.append(AlignedSent( ["gelas", "itu", "bagus" ], \
    ["gelas", "niku", "sae"] , \
    Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))
als.append(AlignedSent( ["jam", "itu", "berbunyi" ], \
    ["jam", "niku", "muni"] , \
    Alignment( [ (0 , 0), (1 , 1), (2 , 2) ] ) ))

"""Korpus paralel untuk pelatihan dengan iterasi sejumlah 100."""

com_ibm1 = IBMModel1(als, 100)

"""Coba cek skor probability alignment 2 kata"""

print(round(com_ibm1.translation_table["makan"]["dahar"], 3) )

print(round(com_ibm1.translation_table["masak"]["masak"], 3) )

print(round(com_ibm1.translation_table["berbunyi"]["muni"], 3) )

als[2].invert()

als[17].invert()

als[19].invert()